### ISSUE TITLE
FAIL Thrall-0.0302 v5.20.1 Windows (Win32)

### ISSUE THREAD

**Issue by sbatschelet** [dex4er/Thrall#6]
This is from November curious if you had any plans to resolve it?

http://www.cpantesters.org/cpan/report/635bc15a-6bf7-1014-a224-f4255d877f5a

Thanks

**Comment by richardleach** [comment]
I get similar errors using v5.22.1 on Windows 10, and they seem to relate to IPv4 / IPv6 confusion.

In `05server-header.t`, requests are made for `http://localhost:$port/` and are unsuccessful: `No connection could be made because the target machine actively refused it.`
The server has been correctly started and is listening, but on `http://127.0.0.1:$port/`, whereas `localhost` resolves to `::1`.
